### ISSUE TITLE
[Documentation]: Compatibility matrix for 6.3.0 requires login

### ISSUE THREAD

**Issue by rafrafek** [ROCm/rocm-docs-core#1053]
### Description of errors

By going to https://rocm.docs.amd.com/en/develop/about/release-notes.html#operating-system-and-hardware-support-changes and clicking [Compatibility matrix](https://rocm.docs.amd.com/en/docs-6.3.0/compatibility/compatibility-matrix.html) I'm being redirected to Log in page.

### Attach any links, screenshots, or additional evidence you think will be helpful.

![image](https://github.com/user-attachments/assets/65ded3f5-be06-44af-88fb-55bcae99a56d)

**Comment by ppanchad-amd** [comment]
Hi @rafrafek. Internal ticket has been created to fix this issue. Thanks!

**Comment by rafrafek** [comment]
I think it works now! Thank you for looking into this! 🙏
