### ISSUE TITLE
Change docs build directory to build/docs

### ISSUE THREAD

**Issue by saadrahim** [ROCm/rocm-docs-core#14]
To change the output directory for sphinx we should change the argument passed into the doctree pickles `-d` and `<outputdir>`

Ref: https://www.sphinx-doc.org/en/master/man/sphinx-build.html

Before:
`python3 -m sphinx -T -E -b html -d _build/doctrees -D language=en . _build/html`
After:
`python3 -m sphinx -T -E -b html -d build/doctrees -D language=en . build/html`

**Comment by saadrahim** [comment]
This is lower priority but please get around to it.

**Comment by samjwu** [comment]
`build` and `_build` are being added to the .gitignore files so that these won't appear in the repository on GitHub
