### ISSUE TITLE
Unneeded internet access

### ISSUE THREAD

**Issue by amd-isparry** [ROCm/rocm-docs-core#182]
When building the documentation for hipcc, which uses this package, the system attempts to download inventories (objects.inv) files from the 3 repos listed in the intersphinx_mapping around https://github.com/RadeonOpenCompute/rocm-docs-core/blob/develop/src/rocm_docs/core.py#L91 and generates warnings if they can't be downloaded.

All this appears to do is slow the build down. The generated documentation appears to be the same regardless of the success/failure of the download.

**Comment by samjwu** [comment]
Addressed in https://github.com/ROCm/rocm-docs-core/pull/443

By setting `external_projects` in `conf.py` to empty to avoid fetching inventories
