### ISSUE TITLE
Add version numbers to generated documentation

### ISSUE THREAD

**Issue by samjwu** [ROCm/rocm-docs-core#22]
The built documentation should have the version number somewhere

**Comment by saadrahim** [comment]
Parse https://github.com/ROCmSoftwarePlatform/rocRAND/blob/aa2ffe613874ed304cd6d5cb86fa0b8f690ba9b1/CMakeLists.txt#L163
if it exists

Append to Documentation Name.

e.g. rocRAND 2.5.0

We can drop the Documentation word in the setup
https://github.com/ROCmSoftwarePlatform/rocRAND/blob/aa2ffe613874ed304cd6d5cb86fa0b8f690ba9b1/docs/conf.py#L9
would no longer have Documentation in it.

Add an optional version number override if CMakeLists.txt does not have the version.

**Comment by samjwu** [comment]
Example conf.py:

```
import subprocess
from rocm_docs import ROCmDocs

getVersionCmd = r'sed -n -e "s/^.*VERSION_STRING.* \"\([0-9\.]\{1,\}\).*/\1/p" ../CMakeLists.txt'
version = subprocess.getoutput(getVersionCmd)
if len(version) == 0:
    version = '1.0.0' # optional version number override if CMakeLists.txt does not have the version

docs_core = ROCmDocs("hipBLAS {}".format(version))
docs_core.run_doxygen()
docs_core.setup()

for sphinx_var in ROCmDocs.SPHINX_VARS:
    globals()[sphinx_var] = getattr(docs_core, sphinx_var)
```

Consider using regular expression in Python for rocm-docs-core

**Comment by saadrahim** [comment]
This needs a little more work. There are many different ways to define versioning, let's support them all.

**Comment by samjwu** [comment]
Get the version from CMakeLists.txt
Use rocm_setup_version string by default
If it doesn't exist, do custom regex in conf.py

example: rocBLAS
`rocm_setup_version( VERSION ${VERSION_STRING} )`

**Comment by samjwu** [comment]
Tracking doc standards in https://github.com/RadeonOpenCompute/rocm-docs-core/issues/330
