### ISSUE TITLE
Customize Page titles to include version similar to header text

### ISSUE THREAD

**Issue by saadrahim** [ROCm/rocm-docs-core#274]
![image](https://github.com/RadeonOpenCompute/rocm-docs-core/assets/44449863/50994bd2-2024-4687-ac3f-3cc1e2405192)
should show ROCm version

**Comment by saadrahim** [comment]
Please see https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_title

**Comment by samjwu** [comment]
Done for docs 5.0.0 to 5.6.0 branches

Example: https://rocm.docs.amd.com/en/docs-5.0.0/
