### ISSUE TITLE
v0.18.3 breaks TOC generation

### ISSUE THREAD

**Issue by MathiasMagnus** [ROCm/rocm-docs-core#277]
[This](https://github.com/RadeonOpenCompute/rocm-docs-core/commit/2380ee069025158d1063d8b839a0c02146efe425) commit doesn't only add projects, but also renames them (seemingly for cosmetic reasons). This breaks TOC generation for all docs even in retrospect. The point of this file is to give stable names to links which may potentially change overtime.

Changing `migraphx` to `amdmigraphx` and `composable-kernel` to `composable_kernel` breaks all working branches, but will also break all of the backported and non-latest branched versions of the docs.

Please revert the aesthetic changes, which isn't worth the effort of having to update and retag all our pre-existing docs.

**Comment by samjwu** [comment]
The intention was to have the naming consistent with GitHub repository names in order to avoid having to reference the `projects.yaml`

My plan is to back-port these changes for ROCm along with the requirements, since that also needs to be updated

What are your thoughts on this?

**Comment by samjwu** [comment]
Backported in https://github.com/RadeonOpenCompute/ROCm `docs/5.x.x` branches
