### ISSUE TITLE
Pitchfork project layout

### ISSUE THREAD

**Issue by MathiasMagnus** [ROCm/rocm-docs-core#313]
AFAIK it is the intention to follow the [Pitchfork project layout](https://api.csswg.org/bikeshed/?force=1&url=https://raw.githubusercontent.com/vector-of-bool/pitchfork/develop/data/spec.bs). If that is the case, I would like to suggest moving as many of the hidden configuration files in the root of the project into a `tools` folder, as per [§ 2.8](https://api.csswg.org/bikeshed/?force=1&url=https://raw.githubusercontent.com/vector-of-bool/pitchfork/develop/data/spec.bs#tld.tools) of the spec:

> The tools/ directory is designated for holding extra scripts and tools related to developing and contributing to the project. For example, turn-key build scripts, linting scripts, code-generation scripts, test scripts, or other tools that may be useful to a project develop.
> 
> The contents of this directory should not be relevant to a project consumer.

At the time of writing this touches upon the following files:

- .markdownlint-cli2.yaml
- .pre-commit-config.yaml
- .readthedocs.yaml
- .spellcheck.yaml
- .wordlist.txt

There are more hidden files which aren't needed for users of the project, but some are location-sensitive and can't be placed elsewhere:

- .dockerignore
- .gitignore
- .gitpod.yml

**Comment by saadrahim** [comment]
I don't think we can move on these things. Its a nice to have but for now let's do other priority tasks.
