### ISSUE TITLE
Version substition

### ISSUE THREAD

**Issue by Naraenda** [ROCm/rocm-docs-core#359]
## Problem case

Currently in main ROCm documentation, versions are kept up to date manually.
Updating this is error prone (i.e. forgetting to update a string).
Having a mechanism to do this programmatically would help greatly.

Myst already has substitutions, but this does not work within code blocks, which is mainly used for showing install instructions.

## Possible solutions

- Add a simple string replace pre-processing step.

- There is a sphinx extension that might do the job, however this does not work with Myst. There is a PR that resolves that but requires additional fix-ups to get merged: https://github.com/adamtheturtle/sphinx-substitution-extensions/pull/235

- Add a Jinja (or other templating engine) pre-processing step that processes `*.md.jinja` or `*.jinja.md`-files first before cotinuining with normal Myst/Sphinx steps.
  - Myst already has some form of Jinja support with substitutions, so this might conflict.
  - Depending on your point of view, this might be useful/overkill.

**Comment by saadrahim** [comment]
I think you did a lot of this. Worth updating the status.

**Comment by adamtheturtle** [comment]
@Naraenda The latest release of [`sphinx-substitution-extensions`](https://github.com/adamtheturtle/sphinx-substitution-extensions) now has support for `code-block` with MyST.

**Comment by neon60** [comment]
I think we can close this issue. This was needed for the installation guide and that was ported to ReST files.
I could not find any place, where we need to use substitution in MyST files and the extension owner added the support.

**Comment by neon60** [comment]
> @Naraenda The latest release of [`sphinx-substitution-extensions`](https://github.com/adamtheturtle/sphinx-substitution-extensions) now has support for `code-block` with MyST.

@adamtheturtle thanks for the notice and work.
