### ISSUE TITLE
rocm-docs-core should be a sphinx extension

### ISSUE THREAD

**Issue by Maetveis** [ROCm/rocm-docs-core#37]
As noted in [#32](https://github.com/RadeonOpenCompute/rocm-docs-core/pull/32/files#diff-9c6018c1dd12072d86e794cf8163334ee8bc7d69ee21b4c1c68fecd62d0d9f3eR196-R201) rocm-docs-core should provide all of its functionality as a sphinx extension.

The sphinx API seems to provide all the features that rocm-docs-core needs (i.e. requiring other extensions, modifying settings, installing files.)

This would: 
- clean up the consumer interface (no more copying variables into the global scope)
- clean up rocm-docs-core internals (it is currently partly a plugin and partly not, some code is duplicated so that calls from clients can happen in any order)
- would allow for more modularization making parts of the project useful outside of rocm documentation (i.e. running doxygen and doxysphinx automatically)

**Comment by lawruble13** [comment]
Absolutely agreed, I have been saying this for some time but haven't found the time to do it yet.
