### ISSUE TITLE
File copy might be needlessly complicated

### ISSUE THREAD

**Issue by Maetveis** [ROCm/rocm-docs-core#38]
The file copy in rocm-docs core makes use of the handwritten `copy_from_package` function: 
https://github.com/RadeonOpenCompute/rocm-docs-core/blob/e9c03741abeb0f8043943ce65e16e0d37d6d5de5/src/rocm_docs/__init__.py#L310-L333

This is the same as [`shutil.copytree`](https://docs.python.org/3/library/shutil.html#shutil.copytree) outside of the custom error message. Is there some hidden problem with the standard library method or can this be simplified?

**Comment by Maetveis** [comment]
I now realize this is probably because `importlib.resources` doesn't return actual files, but just ["Traversable" objects](https://docs.python.org/3/library/importlib.resources.abc.html#importlib.resources.abc.Traversable). When the minimum python version is raised 3.9, then this could be simplified as mentioned in the first comment by calling `as_file()` first.

**Comment by lawruble13** [comment]
Yes, that's exactly correct, it is due to how importlib returns the information to us. I'm not inherently opposed to upgrading the python version, although that would be a lot of changes at this point in time.

**Comment by Maetveis** [comment]
> I'm not inherently opposed to upgrading the python version, although that would be a lot of changes at this point in time.

I'm not proposing that, I agree it would be hassle for little gain. Python 3.8 is the default in ubuntu 20.04 (3.9 is available in apt, however), just wanted to note that this discussion can be revisited if/when its raised.

**Comment by sohaibnd** [comment]
Hi @Maetveis, sorry for the very late response. Thanks for the suggestion, I have replaced `copy_from_package` with `shutil.copytree` in #1075. Closing this issue.
