### ISSUE TITLE
Generated files in source tree 

### ISSUE THREAD

**Issue by Maetveis** [ROCm/rocm-docs-core#410]
There are couple functions where `rocm-docs-core` will write to the sphinx source directory,
this is not a nice practice and we should try to clean these up. Following is a summary of these, why they are needed and what can be done to fix them:

## Doxygen and Doxysphinx generated sources
Doxygen generates HMTL documentation, and Doxysphinx creates `.rst` documents that include these using [the `.. raw::` directive](https://docutils.sourceforge.io/docs/ref/rst/directives.html#raw-data-pass-through).

Fixing this would entail:
- Storing the HTML files outside of the source tree
- Sphinx growing an API for pages in the documentation that are completely generated
- Doxysphinx growing up to become a sphinx extension (instead of a cli tool it is currently) and using said API and providing `Docutils` ast to sphinx instead of rst files.

## `_toc.yml.in`
We are doing some templating on the contents of `toc.yml`.

Ideally [`sphinx_external_toc`](https://github.com/executablebooks/sphinx-external-toc) could be taught to take its input from an in-program API and not parse a file, then we could do the transformation in-memory and wouldn't need to write it to disk.

Note this is sooo close to being possible, the extension already has an API to parse the yaml file and [also stores it in the config](https://github.com/executablebooks/sphinx-external-toc/blob/4e83bb683104a8b3347033d35eb58656135a015a/sphinx_external_toc/events.py#L77) in a documented format.

## 404.md 
We copy a 404 page markdown into the source tree, to have a unified not found page on all sites.
#407 solves this one

I hope I didn't miss any, @MathiasMagnus should be able to confirm since he's fighting the battle to work around these.

**Comment by parbenc** [comment]
The _toc.yml generation right now couldn't be moved, but the _doxygen library generated in some cases has been moved.
