### ISSUE TITLE
Increase ToC depth

### ISSUE THREAD

**Issue by LisaDelaney** [ROCm/rocm-docs-core#413]
The current table of contents is limited to 4 items in depth and with the new ROCm docs structure, we're going to need to increase this to 5.

**Comment by saadrahim** [comment]
https://github.com/executablebooks/sphinx-book-theme/blob/a9794b73cec766e01bee35a96f7d44e22851f278/src/sphinx_book_theme/theme/sphinx_book_theme/components/sbt-sidebar-nav.html#L20

We need to override the settings above.

**Comment by Maetveis** [comment]
The PR linked above makes this option configurable in our base theme sphinx-book-theme, it's a over a year old, but I pinged the owners.
replacing `"sphinx-book-theme>=1.0.1` with `package-two @ git+https://github.com/StreamHPC/sphinx-book-theme@gbw-additional-theme-customisation` in pyproject.toml allows testing this locally.

**Comment by samjwu** [comment]
https://sphinx-external-toc.readthedocs.io/en/latest/user_guide/sphinx.html#toc-tree-options
