### ISSUE TITLE
Add sphinx-sitemap extension

### ISSUE THREAD

**Issue by samjwu** [ROCm/rocm-docs-core#43]

**Comment by saadrahim** [comment]
https://docs.readthedocs.io/en/stable/reference/sitemaps.html Looks like this is not needed.

**Comment by samjwu** [comment]
Read the Docs automatically generates a sitemap.xml for your project,

By default the sitemap includes:

    Each version of your documentation and when it was last updated, sorted by version number.

This allows search engines to prioritize results based on the version number, sorted by [semantic versioning](https://semver.org/).

**Comment by saadrahim** [comment]
I wonder if it can sort our versions since we don't use semantiv versioning. We use rocm-x.y.z
