### ISSUE TITLE
Fix hover message on Intersphinx links

### ISSUE THREAD

**Issue by samjwu** [ROCm/rocm-docs-core#470]
Example: https://rocm.docs.amd.com/en/latest/reference/all.html

(in Python)

shows up when hovering over a link

**Comment by Maetveis** [comment]
That value seems to be constructed from the [`project`](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-project) and [`release`](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-version) sphinx options.

For the legacy API, we can set this up based on the `project_name` parameter, which will fix this for most projects. For extension based users they should just set these options.

**Comment by Maetveis** [comment]
For example rocAL links have the hover "in rocAL Documentation v1.0.0" because [their conf.py has these settings](https://github.com/ROCmSoftwarePlatform/rocAL/blob/b290600652f28078911b976cf4bf70dd7068e1c6/docs/conf.py#L41-L46)

**Comment by samjwu** [comment]
will be fixed as part of https://github.com/RadeonOpenCompute/rocm-docs-core/issues/330
