### ISSUE TITLE
Linting workflow should be available locally

### ISSUE THREAD

**Issue by Maetveis** [ROCm/rocm-docs-core#489]
Currently the linting workflow [.github/workflows/linting.yml](https://github.com/RadeonOpenCompute/ROCm/blob/aa5eff25fb7927e65eb677cf813353999ce7bf23/.github/workflows/linting.yml) is only available as a GitHub action.

Being able to run this before making a PR would make development experience nicer. Additionally if the core of the action is based on a command line tool it is much easier to re-use it in different CI environments, like GitLab workflows.

The easiest way is probably to turn the checks into [pre-commit](https://pre-commit.com/) hooks. rocm-docs-core already uses those, and they are very easy to re-use from other repositories.

**Comment by sohaibnd** [comment]
Hi @Maetveis, sorry for the delay. Which repository are you contributing to that you think could use the pre-commit hooks and why are the GitHub actions not sufficient?

**Comment by Maetveis** [comment]
> Hi @Maetveis, sorry for the delay.

🤣

I am no longer and unlikely to be an active contributor in ROCm documentation.

In general I prefer locally runnable linting because of the latency of gh actions. Feel free to close this, I'm not personally interested anymore, though summoning @MKKnorr, who is AFAIK still active in this space.

**Comment by sohaibnd** [comment]
Understood, sorry about that. Note that there is a tool called [act](https://github.com/nektos/act) that you can use to run your GitHub Actions locally in general.

Closing this issue.
