### ISSUE TITLE
New link strategy for returning from subprojects to main project

### ISSUE THREAD

**Issue by saadrahim** [ROCm/rocm-docs-core#534]
Two different links back to the main page based on project

# APIs and tools subprojects
All the subprojects linked from the new API and tools page will get a different link back to main page.

Return to the API and ref home page

The link back the API and home page should be called "ROCm APIs & tools list"

# Installation subprojects
return to the main ROCm page documentation page. i.e. current behaviour maintained

**Comment by samjwu** [comment]
theme name
rocm-api-tools-list

**Comment by samjwu** [comment]
main theme
- left nav links to api tools list page https://rocm.docs.amd.com/en/develop/reference/library-index.html

sub theme (name: rocm-docs-home)
- left nav links to https://rocm.docs.amd.com/

**Comment by samjwu** [comment]
default: left nav points to api/tools list page
- applies to most projects

home flavor: left nav points to rocm docs home page
- applies to rocm and install guides

**Comment by samjwu** [comment]
applies in v0.30.3
