### ISSUE TITLE
The redirect home link on 404 Pages sometimes leads to another 404 Page

### ISSUE THREAD

**Issue by xu-shawn** [ROCm/rocm-docs-core#565]
Here is the HTML code of the link in question:

```html
<p>Return <a href="index.html">home</a>
```

It uses a relative URL, which directs the user to the index.html of the same directory path as the current page. However this file does not exist on all directories, which may lead another 404. [Example](https://rocm.docs.amd.com/projects/radeon/en/latest/docs/compatibility).

**Comment by samjwu** [comment]
Fixed in https://github.com/ROCm/rocm-docs-core/blob/develop/src/rocm_docs/rocm_docs_theme/404.html
