### ISSUE TITLE
Add common keywords to metadata

### ISSUE THREAD

**Issue by samjwu** [ROCm/rocm-docs-core#585]
add keywords to metadata for all projects

keywords: AMD, ROCm, (project name)

eg:

```
<head>
  ...
  <meta name="keywords" content="AMD, ROCm, (project name)">
  ...
</head>
```

**Comment by LisaDelaney** [comment]
With that format...how do we avoid replacing the existing header?

**Comment by samjwu** [comment]
According to https://stackoverflow.com/questions/7355623/is-it-wrong-to-add-multiple-meta-keywords-and-description-occurrence-in-head, it seems indexers may not accept multiple meta tags for keywords

As each page needs its own title and keywords, will not be implementing this in favor of adding them individually
